### ISSUE TITLE
Kodeketa arazoak zenbait hiztegitan

### ISSUE THREAD

**Issue by asiersarasua** [euskalbar/euskalbar#164]
Zenbait hiztegitan ez dira ongi ebazten kodeketa arazoak. 
- Hitza sartzean, hitzak azentua, eñea edo antzekoa badu, ez da bilaketa ongi egiten.
 - Euskalterm
- Emaitza erakustean bilaketa konbinatuetan, ez dira ongi erakusten.
 - Adorez

**Comment by asiersarasua** [comment]
Beno, zuzenean Euskaltermen webgunean kontsulta eginda (adib. "cigüeña") ere ez du funtzionatzen; beraz, issue hau itxiko dut.

**Comment by julen** [comment]
Zer ez dabil webgunean? Euskalbarren aldetik kodeketa ez da arazoa, datuak bidaltzeko metodoa baizik.

**Comment by asiersarasua** [comment]
Euskaltermen webgunera[1] joan, aukeratu "Gaztelania" hizkuntza, eta bilatu "cigüeña" edo "caña", eta ez du emaitza zuzenik itzultzen. Euskaraz bilatu "zikoina" edo "kanabera", eta emaitza zuzenak itzultzen ditu.

[1]http://www.euskara.euskadi.net/q91EusTermWar/kontsultaJSP/q91aAction.do

**Comment by julen** [comment]
Bai, hori apurtuta dago: `cigüeña` emaitza lortzeko modu bakarr `cig%` idatzita da.
