### ISSUE TITLE
Bilaketa-proposamenak Euskalbarren

### ISSUE THREAD

**Issue by Nipisek** [euskalbar/euskalbar#179]
Hitz bat sartzen dugunean hiztegian, faltan botatzen dut motoreak proposamenak egitea. Alegia: 'hiz' idatzita 'hizkuntza', 'hiztegi', 'hizlari' eta tanketako zerrenda zabaltzea.
Euskaraz eta gaztelaniaz ari garenean arazoa ez da hain handia, baina atzerriko beste hizkuntza batean ari bagara, grafia ez badugu dominatzen, edo, besterik gabe, denbora aurrezteko, faltan botatzen dut motoreak proposamenik ez egitea, adibidez Wordreferencek egiten duen bezala.

Agian norbaitek egingo zuen proposamen hau baina...
Eskerrik asko!

**Comment by asiersarasua** [comment]
Fixed in 4dde47e688f336a354a7701a9b49e7f7a726ac08

Orain, Euskalbarren bilaketa-kutxan iradokizunak erakusten dira. Firefoxen bilaketa-motorren kutxa nagusian erakusten diren iradokizun berak dira. 

Horrez gain, bilaketa-kutxa hutsik dagoenean "Euskalbar" hitza ikusten da leku-marka gisa.

**Comment by julen** [comment]
Egiteko erraza izan arren, ez dut uste 4dde47e-ko inplementazioa egokia denik.

Batetik, gomendioak bilaketa-motor lehenetsiarekin lotzen ditu eta, esango nuke motor hori Google izatea onartzen dela nolabait. Erabiltzaileek hau aldatzeko aukera dute eta, kasu horretan, lortutako emaitzak oso desberdinak izan daitezke eta azken batean erabiltzailearen esperientzia irregularra da.

Bestetik, Google motor lehenetsia den kasuan, beste hizkuntzetako emaitza erabilgaitz asko datoz bueltan. Hau da, positibo faltsuak nabarmentzen dira. Egoera okerragoa izan daiteke bilaketak EHtik kanpo egitean.

Azkenik, pribatutasuna. Idazten den karaktere oro bilatzailera bidaltzen ari gara eta ez dago eginkizuna desaktibatzeko modurik.

Hau esanda, erabiltzaile nahiz garatzaile gisa ez nintzateke eroso sentituko Euskalbarrek inplementazio hau argitaratuko balu.

**Comment by asiersarasua** [comment]
Ados, bilaketan erabiltzaileak lehendik sartutako hitzak *bakarrik* itzultzeko modua begiratu beharko da.

Horrez gain, agian aukera berri bat sor daiteke, hobespenen leihoan, erabiltzaileak beste iradokizun horiek *ere* jaso ditzan.

**Comment by julen** [comment]
Ulertzen dudanagatik, eta issue honen oinarrira bueltatuta, eskaini nahi den eginbidea da hitzak automatikoki osatzea, baina ez aurrez egindako bilaketetan oinarrituta, nolabait hainbat hizkuntza bilduko lituzkeen hiztegi edo DB bat erabiliz. Begiratu wordreference.com guneak egiten duena, adibidez.

**Comment by asiersarasua** [comment]
Bai, ulertzen dut. Baina hori egiteko, kanpoko hornitzaile batek eman beharko dizkigu hitzak osatzeko iradokizunak, ezta? Guk ezin ditugu hainbat hizkuntzako hiztegiak integratu Euskalbarren.

**Comment by julen** [comment]
Hala da, bai. Hornitzaile hori bilaketa-motor bat izatea ez dut uste egokiegia denik goian aipatutako arrazoiengatik. Halako zerbitzurik ez dagoenez, gerorrek sortu beharko genukeen bat; ez da lan makala aurreikusiko duzun moduan.

Bilaketa-iradokizunak offline ere eman litezke, baina baliabideak bezeroan jarri beharko lirateke kasu horretan eta ez litzateke oso eraginkorra izango: xpi-aren pisua asko handituko zen, parekatzeko moduak makalak gerta daitezke bezeroan, edukien jatorriaren arabera lizentzia-arazoak egon daitezke...

**Comment by asiersarasua** [comment]
Agian ortografia-egiaztatzailearen bidez... Lehenengo, jatorrizko hizkuntzarako egiaztatzailea instalatuta dagoen ala ez egiaztatu beharo litzateke.

https://developer.mozilla.org/en-US/docs/Using_spell_checking_in_XUL

**Comment by asiersarasua** [comment]
Eginda ortografia-egiaztatzailearen bidez. Bide batez @julen Mozillaren webguneko Xuxen-ek[1] dio ez dela bateragarria Fx 37 bertsioarekin.
