### ISSUE TITLE
Ertzaintzaren hiztegia Euskalbarren txertatzeko eskaera

### ISSUE THREAD

**Issue by AlesBengoetxea** [euskalbar/euskalbar#183]
Udaleko langile batzuek euskalbar oso tresna eraginkorra dela adierazi didate, baina hobekuntza bat proposatzen dute: Ertzaintzaren hiztegia ere bertan sartzea.
Ertzaintzaren hiztegia ondoko helbide honetan dago:
http://ttiki.com/62551

(Forma laburtuta erabiliz gero, ez dabil zehaztasunez)
Helbide osoa:
http://www.ertzaintza.net/wps/portal/ertzaintza/!ut/p/c5/04_SB8K8xLLM9MSSzPy8xBz9CP0os3gXDydTo2AzN0tLE9dAdxNzDxdzAwgAykeaxRvgAI4GBHSHg-wzi_f38QwzDTR2dHc0CXX28gkMdDKEqQDL4zHfzyM_N1W_IDfCIMvEUREAQNwh_Q!!/dl3/d3/L2dJQSEvUUt3QS9ZQnZ3LzZfSUYzSFVWRjAwRzVGMTBJUEwwU0RWUUlJMTA!/

Langile horien izenean eta geurean, mila-mila esker!!!

**Comment by asiersarasua** [comment]
Ez dut ondo ulertzen hiztegi horren funtzionamendua: euskarazko hitzak bilatzen saiatzen naiz, eta ez dabil, nahiz eta EU-ES, EU-EN, EU-FR dirudien. Gaztelaniazkoak soilik bila al daitezke?

**Comment by asiersarasua** [comment]
Helbide zuzena honek dirudi:
http://www.ertzaintza.net/wps/portal/ertzaintza/!ut/p/c5/04_SB8K8xLLM9MSSzPy8xBz9CP0os3hPN2OP0DA3AwN3UzdDA88AH4Ngl7BAT09DA6B8pFm8AQ7gaADS7eLhZGoUbOZmaWniGuhuYu7hYg6Vh-j29_EMMw00dnR3NAl19vIJDHQyhMnjtzsc5Fr8-kHy-FyHzX3mfuYo-tHlw3zh8n4e-bmp-gW5oREGmZ66ACWUqmU!/dl3/d3/L0lDU0lKSWdrbUNTUS9JUFJBQUlpQ2dBek15cXpHWUEhIS80QkVqOG8wRmxHaXQtYlhwQUh0Qi83X0lGM0hVVkYwMEc1RjEwSVBMMFNEVlFJSTkyL0NudGRGMzI2ODAwMDMvc2Euc3BmX0FjdGlvbkxpc3RlbmVy/?PC_7_IF3HUVF00G5F10IPL0SDVQII92029066_spf_strutsAction=!2fhtml!2fview!2fmenuControllerAction.do!3faccion%3d!2finicializarTerminologiaErtzaintza.do!26opcion%3dboton.terminologia!26nombreMenu%3dmenuGeneral#7_IF3HUVF00G5F10IPL0SDVQII92

Hala ere, URL horrekin saiatu naiz, baina ez dirudi Euskalbar bidez hiztegi horren kontsulta egin daitekeenik.

**Comment by AlesBengoetxea** [comment]
Eskerrik asko, Asier, egindako ahaleginagatik.





                                                                                                     
  Ales Bengoetxea Telletxea        Euskara Zerbitzua - Euskararen Hiria                              
  Euskara Zerbitzua - Hizkuntza                                                                      
  normalizatzailea                                                                                   
  ales_bengoetxea@donostia.org                                                                       
  www.euskaraz.net -                                                                                 
  www.merkatari.net                                                                                  
  Tel: 943 483759 - Faxa: 943                                                                        
  483765                                                                                             
  Konstituzio plaza 2, behea.                                                                        
  20003 Donostia.                                                                                    
                                                                                                     






Nork:	asiersarasua <notifications@github.com>
Nori:	euskalbar/euskalbar <euskalbar@noreply.github.com>
cc:	AlesBengoetxea <Ales_Bengoetxea@donostia.org>
Data:	08/04/2015 12:49
Gaia:	Re: [euskalbar] Ertzaintzaren hiztegia Euskalbarren txertatzeko
            eskaera (#183)



Helbide zuzena honek dirudi:
http://www.ertzaintza.net/wps/portal/ertzaintza/!ut/p/c5/04_SB8K8xLLM9MSSzPy8xBz9CP0os3hPN2OP0DA3AwN3UzdDA88AH4Ngl7BAT09DA6B8pFm8AQ7gaADS7eLhZGoUbOZmaWniGuhuYu7hYg6Vh-j29_EMMw00dnR3NAl19vIJDHQyhMnjtzsc5Fr8-kHy-FyHzX3mfuYo-tHlw3zh8n4e-bmp-gW5oREGmZ66ACWUqmU!/dl3/d3/L0lDU0lKSWdrbUNTUS9JUFJBQUlpQ2dBek15cXpHWUEhIS80QkVqOG8
 wRmxHaXQ
tYlhwQUh0Qi83X0lGM0hVVkYwMEc1RjEwSVBMMFNEVlFJSTkyL0NudGRGMzI2ODAwMDMvc2Euc3BmX0FjdGlvbkxpc3RlbmVy/?PC_7_IF3HUVF00G5F10IPL0SDVQII92029066_spf_strutsAction=!2fhtml!2fview!2fmenuControllerAction.do!3faccion%3d!2finicializarTerminologiaErtzaintza.do!26opcion%3dboton.terminologia!26nombreMenu%3dmenuGeneral#7_IF3HUVF00G5F10IPL0SDVQII92


Hala ere, URL horrekin saiatu naiz, baina ez dirudi Euskalbar bidez hiztegi
horren kontsulta egin daitekeenik.


—
Reply to this email directly or view it on GitHub.

Hemendik aurrera nire posta elektronikoa  "donostia.eus"  domeinura aldatuko da. Hori dela eta, gomendatzen dizut nire posta elektroniko berria zure kontaktuetan gordetzea.  A partir de ahora mi correo electrónico cambia el dominio a  "donostia.eus"  y en consecuencia, le recomiendo que guarde mi nueva dirección electrónica en sus contactos. From now, my email change his domain name to  "donostia.eus" . In consecuence, please update your addressbook with my new email. Attention, à partir de maintenant, mon email change de domaine pour  "donostia.eus" . Veuillez mettre à jour mon email dans votre carnet d'adresse.

**Comment by asiersarasua** [comment]
Momentuz, hiztegia dagoen bezala, ezin da Euskalbarren integratu. Beraz, itxi egingo dut issue-a.
