### ISSUE TITLE
"Bilaketaren ondoren, fokua leihoan jarri" alderantziz dabil

### ISSUE THREAD

**Issue by asiersarasua** [euskalbar/euskalbar#203]

**Comment by julen** [comment]
Kontua da [leihoaren fokua ez dela inolaz ere aldatzen](https://github.com/euskalbar/euskalbar/blob/7a4fcbe811cc195006a16ebc6c42092e26e1af4d/src/chrome/content/app.js#L379): fokua testu-kutxan ipintzen da eta bertako testua hautatzen da. Nabigatzailearen lehenetsitako portaera fokua fitxa berrian ipintzea da.

**Comment by asiersarasua** [comment]
Bai, jokabidea azaltzen duen katea gaizki dago: "Bilaketaren ondoren, bilaketa-kutxako testua hautatu" edo horrelako zerbait izan beharko luke. Dena den, alderantziz dabil.

**Comment by asiersarasua** [comment]
Barkatu, nahastu egin naiz, ongi zebilen. Alderantziz ulertu dut. Hala ere, uste dut argiagoa dela kontrakoa, alegia "Bilaketaren ondoren, fokua bilaketa-kutxan jarri"
