### ISSUE TITLE
Euskalbar eguneratu prozesu anitzeko Firefoxekin funtziona dezan

### ISSUE THREAD

**Issue by asiersarasua** [euskalbar/euskalbar#206]
MultiProccess Firefox, nightly kanalean dago jadanik. Seguru asko, Euskalbarrek ez du funtzionatuko berrikuntza horrekin.
https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by asiersarasua** [comment]
NIghtly bertsioarekin probatuta (Firefox 40 izango dena), ez dute funtzionatzen:
- POST bidez kontsultatzen diren hiztegiak
- Bilaketa konbinatuak

**Comment by asiersarasua** [comment]
Badirudi bilaketa konbinatuak badabiltzala.

**Comment by asiersarasua** [comment]
Mozillatik jasotako mezua:

"Dear add-on developer,

You might have heard the news[1] that future versions of Firefox will run the browser UI separately from web content. This is called Multi-process Firefox (also "Electrolysis" or "e10s")[2], and it is scheduled for release in the first quarter of 2016[3].

If your add-on code accesses web content directly, using an overlay extension[4], a bootstrapped extension[5], or low-level SDK APIs[6] like window/utils or tabs/utils, then you will probably be affected.

To minimize the impact on users of your add-ons, we are urging you to test your add-ons[7] for compatibility. You can find documentation on how to make them compatible here[8].

Starting Nov. 24, 2015, we are available to assist you every Tuesday in the #addons channel on irc.mozilla.org[9]. Click here[10] to see the schedule. Whether you need help testing or making your add-ons compatible, we're here to help!

Sincerely,
The Add-ons Team

[1] https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/
[2] https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox
[3] https://wiki.mozilla.org/Electrolysis#Schedule
[4] https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions
[5] https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions
[6] https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs
[7] https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Testing
[8] https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Updating_your_code
[9] irc://irc.mozilla.org/addons
[10] https://atsay.github.io/e10s_office_hours/"

**Comment by e-gor** [comment]
Mozillaren test automatikoek esaten dute Euskalbar MultiProccess Firefox-ekin bateragarria dela:

```
Validation Results for euskalbar-4.4-fx.xpi
Validated at: 	October 12, 2016
Tested for compatibility against: 	Firefox 50.*
Firefox 50 Probak
0 errore, Abisu bat, 0 notices
```

Testean aipatzen duten [https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Testing](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Testing) helbidean dioenaren arabera ere testeatu da eta ongi dabil.

Hala ere, gehigarriak berak deklaratu behar du bateragarria dela etorkizunean Firefox-ek desgaitu ez dezan:

```
Extension is not marked as compatible with Multi Process
Abisua: Your extension is not marked as compatible with Multi-Process Firefox and may not work in future versions of Firefox. Please review it, make changes if needed and set <em:multiprocessCompatible> to true in install.rdf if it's compatible. See https://developer.mozilla.org/docs/Mozilla/Add-ons/Working_with_multiprocess_Firefox for more information.
```

Beraz, aldaketa hori egin da install.rdf fitxategian.

**Comment by egoitzbarrena** [comment]
Kaixo Igor, irakurri dut bidali didazun mezua. Idatzi mezu bat explikatuz zer gertatzen den euskalbarrekin. Uste dut arazoa, baimenen fitxategiarekin zerikusia duela eta horregatik ez du ezer funtzionatzen. Hori ez bada mezu bat bidali eta konpontzen saiatuko naiz.
Ni orain lana bilatzen nago eta angular.js ikasten. Ere hizkuntzan eskolan ingelesa ikasten ari naiz B2 lortzeko.
Zure mezuaren zain gelditzen naiz

Agur 
Egoitz 

    El Jueves 13 de octubre de 2016 10:40, Igor Leturia <notifications@github.com> escribió:
 

 Mozillaren test automatikoek esaten dute Euskalbar MultiProccess Firefox-ekin bateragarria dela:Validation Results for euskalbar-4.4-fx.xpi
Validated at:   October 12, 2016
Tested for compatibility against:   Firefox 50.*
Firefox 50 Probak
0 errore, Abisu bat, 0 notices
Testean aipatzen duten https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox#Testing helbidean dioenaren arabera ere testeatu da eta ongi dabil.Hala ere, gehigarriak berak deklaratu behar du bateragarria dela etorkizunean Firefox-ek desgaitu ez dezan:Extension is not marked as compatible with Multi Process
Abisua: Your extension is not marked as compatible with Multi-Process Firefox and may not work in future versions of Firefox. Please review it, make changes if needed and set <em:multiprocessCompatible> to true in install.rdf if it's compatible. See https://developer.mozilla.org/docs/Mozilla/Add-ons/Working_with_multiprocess_Firefox for more information.
Beraz, aldaketa hori egin da install.rdf fitxategian.—
