### ISSUE TITLE
Euskalterm webgunearen URLa aldatu da eta ez da bilaketa-hitza azaltzen

### ISSUE THREAD

**Issue by wzerbitzua** [euskalbar/euskalbar#216]
Eusko Jaurlaritzak Euskalterm webgunearen URL nagusia aldatu du eta ondorioz, Euskalbarren bitartez bilatutako gako-hitzak ez du emaitzik ematen.
Hau da URLa gaurkotua: http://www.euskara.euskadi.net/r59-euskalte/eu/q91EusTermWar/kontsultaJSP/q91aAction.do

Mesedez, kontuan hartu.

**Comment by julen** [comment]
Kuriosoa, atzo zuzendu zuen helbidea @asiersarasua-k:
http://www.euskara.euskadi.net/r59-15172x/eu/q91EusTermWar/kontsultaJSP/q91aBilaketaAction.do

Zuk proposatutakoaren bestelakoa. Gainera, bilaketa egiterakoan, izenburuan *"Elhuyar hiztegia"* ageri da.

Nik lortzen dudan helbidea hau da (inongo hizkuntzari espezifikoa ez den URLa):
http://www.euskara.euskadi.net/q91EusTermWar/kontsultaJSP/q91aBilaketaAction.do

**Comment by asiersarasua** [comment]
Ehem... orduan zein da helbide zuzena? Kontuan izan dagoeneko bidali dudala bertsio berria AMOra balidatzera.

**Comment by asiersarasua** [comment]
@julen ek proposatutako URLra aldatu dut, baina ez da argitaratuko AMOn dagoen 4.2.1 bertsioan; 5.0 bertsiora itxaron beharko du.
