### ISSUE TITLE
Avoid if possible non crossbrowser keys in manifest.json

### ISSUE THREAD

**Issue by juananpe** [euskalbar/euskalbar#247]
According to MDN, this key is not mandatory:
https://github.com/euskalbar/euskalbar/blob/de8caacf0d8b9e298f95b0254b212593e0cf81f4/src/manifest.json#L10
If we are not using it, would it be possible to delete it? It is generating a warning in Chrome.

**Comment by e-gor** [comment]
It is necessary if you intend to update to AMO an already existing add-on using the API: [https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID#When_do_you_need_an_Add-on_ID](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID#When_do_you_need_an_Add-on_ID).

I suggest leaving it, it is not that much work removing it when bundling it for Chrome...
