### ISSUE TITLE
Etiketa bat esleitu oraingo bertsioari

### ISSUE THREAD

**Issue by juananpe** [euskalbar/euskalbar#251]
Tag berri bat sartu beharko genukeen oraingo kodeari. 5.0, adibidez, baina ez dakit non jarri, nire PR-ak baino lehenagoko commit-an edo uneko commit-an...

**Comment by e-gor** [comment]
Unekoan egin eta kito, errazagoa bada

**Comment by e-gor** [comment]
Ulertzen dut hau egin dela, ezta? Itxiko dut.
