### ISSUE TITLE
Euskalbar sidebar bihurtu

### ISSUE THREAD

**Issue by asiersarasua** [euskalbar/euskalbar#256]
Euskalbar 5.0 berriarekin, jende gehienaren kexa da barra ez dagoela beti bistan: botoia sakatu behar dela hura ikusteko, eta horrek traketsago bihurtzen duela lana.

Euskalbar alboko barra bat bihurtuko balitz, beti bistan geratuko litzateke (baita nabigatzailea itxita eta berriro irekita ere).

Proba bat egin dut eta posible dela ikusi dut (ikusi irudia), baina ez dakit zein punturaino den egingarria, egokia, erabilgarriagoa... ala gauza asko apurtuko diren Euskalbar alboko barra bihurtuta.

Zer iruditzen zaizue?

```
  "sidebar_action": {
    "default_icon": "irudiak/euskalbar64.png",
    "default_title" : "Euskalbar",
    "default_panel": "euskalbar.html"
},
```

![pantaila-argazkia 2017-11-03 18-20-01 e ndik](https://user-images.githubusercontent.com/3200264/32387160-e3c8ef6e-c0c3-11e7-95a2-c0f883715ba8.png)

**Comment by juananpe** [comment]
"Euskalbar 5.0 berriarekin, jende gehienaren kexa da barra ez dagoela beti bistan: botoia sakatu behar dela hura ikusteko, eta horrek traketsago bihurtzen duela lana."

Bai, lehen klik bat egin behar zuten zerbait tekleatzen hasteko eta orain klik bat egin behar dute (ez gehiago, ez gutxiago, berdin). Baina egia da botoi batean klik egitea zailagoa dela testu eremuan klik egitea baino. Dena den, hori konpontzeko sidebar gisa jartzea... pantailaren laurden bat jaten du une oro. Ni ez naiz horren aldekoa, baina ulertzen dut jendearen kexa eta agian batzuk horrela izatea nahiago dute. 

Aukera hori eman daiteke Euskalbar instalatzean? Alegia, sidebar gisa do dagoen moduan uztea?

**Comment by asiersarasua** [comment]
Ez dakit aukera eman daitekeen sidebar edo toolbar gisa jartzeko.

Dena den, estilo pixka bat emanda, iruditzen zait ondo geratzen dela sidebar modura, eta ez duela pantaila zati handirik kentzen. Ikusi irudia. Azken finean, beste alboko barra bat da, historiarena eta laster-markena diren bezala. Nahi duenak bistan eduki dezake, eta nahi ez duenak, ezkutatu.

![pantaila-argazkia 2017-11-04 11-27-18 e ndik](https://user-images.githubusercontent.com/3200264/32404614-257d4f60-c153-11e7-9945-b19e588c8b7b.png)

Bideoa: https://vimeo.com/241292416

**Comment by e-gor** [comment]
Asier Sarasua Garmendia<notifications@github.com> igorleak hau idatzi zuen
(2017(e)ko azaroa 3 18:27):

> Euskalbar 5.0 berriarekin, jende gehienaren kexa da barra ez dagoela beti
> bistan: botoia sakatu behar dela hura ikusteko, eta horrek traketsago
> bihurtzen duela lana.
>

Egia da Euskalbar berria lehengoaren ezberdina dela, baina, esan bezala, ez
da guk hala nahi izan dugulako, behartuta baizik...

Bere garaian bota nuen zerrenda honetan arazoa eta laguntza eskatu, eta
zeuden aukeren artean, Juananek komentatutakoa inplementatu dugu, botoi
batekin barra irekitzearena, alegia.

Egia da honek botoian klik egitea eskatzen duela, eta hori jendeari ez
zaiola gustatu, jaso ditugun kexa eta balorazioen arabera. Beste baterako
utziko ditut kexa horietako batzuen tonuak, exijentziak... Mingarriak izan
dira, ni nahiko moskeatuta nago.

Baina Juananek dioen bezala, lehen ere kutxan klik egin behar zen. Egia da
lehen-lehen bertsioan (5.0an) fokua ez zela kutxara eramaten eta klik bat
gehiago egin behar zela kutxan, baina orain (5.0.1ean) konponduta dago.
Beraz, orain klik bakarra egin behar da, diferentzia bakarra da kutxan edo
botoian egitea, niri ez zait hainbesterako iruditzen...

Gainera, orduan Juananek proposatu zuen bezala, laster tekla bat ere jarri
da (Ktrl+Shift+U). Hori sakatuta barra irekitzen da eta fokua kutxan
jartzen da. Horretara ohituz gero, nire ustez, erosoagoa eta guzti da
saguaren klika baino. Elhuyarreko itzultzaile batzuen artean komentatuta
(Euskalbarren erabiltzaile leialak dira, ezin dira bera gabe bizi), beraiek
ere horrela ikusten zuten. Kontua da jende gehienak ez dituela argibideak
edo ezer irakurtzen eta ez duela laster-teklarena jakingo. Eta jakinda ere,
beste jende askok ez du ohiturarik ez gogorik laster teklak erabiltzeko.
Konbinazioak ikastea (kasu honetan bezala bat bakarrik izanik ere) lan asko
omen... baina ez da ezer gero aurrezten duen lanaren aldean.

Beraz, ez dakit, nik uste dut agian nahikoa dela jendeari 5.0.1
instalatzeko itxarotea eta laster-teklaren inguruko komunikazio edo
pedagogia apur bat egitea, ez?

Euskalbar alboko barra bat bihurtuko balitz, beti bistan geratuko litzateke
> (baita nabigatzailea itxita eta berriro irekita ere).
>
> Proba bat egin dut eta posible dela ikusi dut (ikusi irudia), baina ez
> dakit zein punturaino den egingarria, egokia, erabilgarriagoa... ala gauza
> asko apurtuko diren Euskalbar alboko barra bihurtuta.
>
> Zer iruditzen zaizue?
>

Aukera hori zegoela ikusi nuen, baina nik Juananek bezala pentsatzen dut,
pantailari beti zati hori kentzea gehiegi deritzot. Eta hemen ere
itzultzaile batzuei galdetuta, berdin pentsatzen zuten. Sidebarra egitea
euliak kanoikadaka hiltzea dela iruditzen zait.

Bietako bat aukeratzea utz daitezkeen, ez dakit, baina ez dut uste,
manifest.json fitxategian deklaratzen da bata edo bestea den...

—————————————————

Elhuyarreko helbide elektronikoak @elhuyar.eus dira orain.

Las direcciones electrónicas de Elhuyar son ahora @elhuyar.eus.

Les adresses électroniques d’Elhuyar sont à présent @elhuyar.eus.

Elhuyar's electronic addresses are now @elhuyar.eus.
*Igor Leturia Azkarate*
PROIEKTU-ARDURADUNA / PROJECT MANAGER
<http://scholar.google.com/citations?user=YYp03jkAAAAJ>
<http://www.researchgate.net/profile/Igor_Leturia/>
<https://twitter.com/elhuyarig> <http://www.linkedin.com/in/igorleturia>
<https://www.youtube.com/user/ElhuyarFundazioa1/videos>
<https://www.facebook.com/elhuyar.fundazioa>
*i.leturia@elhuyar.eus* <i.leturia@elhuyar.eus>
Tel.: 943363040 | luzp.: 224

Zelai Haundi, 3
Osinalde industrialdea
20170 Usurbil



*www.elhuyar.eus* <http://www.elhuyar.eus/>
<https://www.elhuyar.eus/eu/site/komunitatea/bazkideak/elhuyarkide-izan>
Mezu honek, baita berarekin doan edozein agirik ere, isilpeko informazioa
izan dezake. Informazio hori jasotzeko baimena izendatutakoak baino ez du.
Zu ez bazara adierazitako hartzailea, indarrean dagoen legeriaren arabera
debekatuta daukazu informazio hori baimenik gabe erabili, hedatu eta/edo
kopiatzea. Mezu hau errakuntza baten ondorioz jaso baduzu, jakinarazi
bidaltzaileari, eta ezaba ezazu. Eskerrik asko.
Ez inprimatu mezu hau ezinbestekoa ez bada.

**Comment by asiersarasua** [comment]
Ados. Niri gero eta gehiago gustatzen zait nola geratzen zaidan Euskalbar sidebar modura, baina nik ez dudanez garapen lan sakonik egiteko gaitasunik eta orain ez nagoenez arduradun, ba zuk nahi duzuna.

Bestalde, sidebar forman ikusi dut POST bidezko eskaerek ez dutela funtzionatzen, eta ez nuke jakingo hori konpontzen, edo denbora asko beharko nuke.

Zenbait erabiltzailek eskariak egitean izaten duten jarrera... niri ere gertatu izan zait lehenago Euskalbarrekin berarekin, zer egingo diogu ba!

Lasterbideari dagokionez, baieztatzeko besterik ez bada: ezin da Ctrl+Alt+A erabili, lehen zegoen bezala, ezta? Irakurri dudanagatik, bigarren tekla ezin da Alt izan...

**Comment by e-gor** [comment]
Asier Sarasua Garmendia<notifications@github.com> igorleak hau idatzi zuen
(2017(e)ko azaroa 4 23:14):

> Ados. Niri gero eta gehiago gustatzen zait nola geratzen zaidan Euskalbar
> sidebar modura, baina nik ez dudanez garapen lan sakonik egiteko gaitasunik
> eta orain ez nagoenez arduradun, ba zuk nahi duzuna.
>
Ez da hori, nik nire iritzia bota dut soilik.

Beste kontu bat, komentatzea ahaztu zitzaidana: jendeari orokorrean ez
zaizkio aldaketak gustatzen, eta Euskalbar-ek izan duen aldaketak
eragindako kexak ikusita, sidebar bihurtzeari jendearen kexak berdin
sortzeko aukera asko ikusten dizkiot...

Bestalde, sidebar forman ikusi dut POST bidezko eskaerek ez dutela
> funtzionatzen, eta ez nuke jakingo hori konpontzen, edo denbora asko
> beharko nuke.
>
> Zenbait erabiltzailek eskariak egitean izaten duten jarrera... niri ere
> gertatu izan zait lehenago Euskalbarrekin berarekin, zer egingo diogu ba!
>
> Lasterbideari dagokionez, baieztatzeko besterik ez bada: ezin da
> Ctrl+Alt+A erabili, lehen zegoen bezala, ezta? Irakurri dudanagatik,
> bigarren tekla ezin da Alt izan...
>

Gauza ahalik eta gehienetan saiatu nintzen lehen zegoen bezala uzten.
Laster tekla ere bera mantentzen saiatu nintzen, baina zuk diozun bezala,
bigarrena ezin da Alt izan. Baina orain ikusi dudanagatik, beharbada
Ktrl+Shift+A libre dago, ez dakit zergatik jarri nuen U...


—————————————————

Elhuyarreko helbide elektronikoak @elhuyar.eus dira orain.

Las direcciones electrónicas de Elhuyar son ahora @elhuyar.eus.

Les adresses électroniques d’Elhuyar sont à présent @elhuyar.eus.

Elhuyar's electronic addresses are now @elhuyar.eus.
*Igor Leturia Azkarate*
PROIEKTU-ARDURADUNA / PROJECT MANAGER
<http://scholar.google.com/citations?user=YYp03jkAAAAJ>
<http://www.researchgate.net/profile/Igor_Leturia/>
<https://twitter.com/elhuyarig> <http://www.linkedin.com/in/igorleturia>
<https://www.youtube.com/user/ElhuyarFundazioa1/videos>
<https://www.facebook.com/elhuyar.fundazioa>
*i.leturia@elhuyar.eus* <i.leturia@elhuyar.eus>
Tel.: 943363040 | luzp.: 224

Zelai Haundi, 3
Osinalde industrialdea
20170 Usurbil



*www.elhuyar.eus* <http://www.elhuyar.eus/>
<https://www.elhuyar.eus/eu/site/komunitatea/bazkideak/elhuyarkide-izan>
Mezu honek, baita berarekin doan edozein agirik ere, isilpeko informazioa
izan dezake. Informazio hori jasotzeko baimena izendatutakoak baino ez du.
Zu ez bazara adierazitako hartzailea, indarrean dagoen legeriaren arabera
debekatuta daukazu informazio hori baimenik gabe erabili, hedatu eta/edo
kopiatzea. Mezu hau errakuntza baten ondorioz jaso baduzu, jakinarazi
bidaltzaileari, eta ezaba ezazu. Eskerrik asko.
Ez inprimatu mezu hau ezinbestekoa ez bada.
