### ISSUE TITLE
Hizkuntzen norabidea aldatzeko tekla konbinazioa

### ISSUE THREAD

**Issue by ElhuyarItzulpenak** [euskalbar/euskalbar#259]
Hizkuntza-bikote berean noranzkoz aldatzeko, Ktrl+A+t+Z sakatzea aski zen lehenago. Orain ez du funtzionatzen tekla-konbinazio horrek, eta nahitaezkoa da hizkuntza-bikoteen zerrendan aukeratzea, saguarekin. Normalean hizkuntza-bikote berarekin eta bi noranzkotan ibiltzen garenontzat oso erabilgarria zen aukera hori.

**Comment by msusperregi** [comment]
"Ctrl + . " tekla konbinazioa jarri dut hizkuntza-bikotearen noranzkoa aldatzeko tekla konbinazioa
