### ISSUE TITLE
Ikonoan klik egitearekin kursorea testua idazteko prest

### ISSUE THREAD

**Issue by FiloBlogia** [euskalbar/euskalbar#260]
Nire iradokizuna hauxe da: EuskalBarren ikonoa sakatzen dugunean, agertzen den lehiatilan kursorea idazteko kutxan egotea, idazteko prest. Berriz, aldez aurretik hitz bat idatzi badugu, hitz hori aukeratuta agertuko litzateke, gainean idazteko prest.
Hori egitea posible balitz, saguaren hainbat mugimendu aurreztuko genituzke, besteak beste.
Eskerrik asko aurrez eta agur bero bat,
R.G.

**Comment by e-gor** [comment]
Bai, funtzionalitate hori oso interesgarria da, eta inplementatuta dago. Baina Firefox-ek akats bat du horretan eta ez dabil ongi. Itzulinguru baten bidez lortu genuen Linux-en ongi ibiltzea, baina Windows-en ez dabil...

**Comment by e-gor** [comment]
Firefox-en eguneraketa baten ondoren, bere akats hori konpondu zuenez, Euskalbar-en arazo hau berez konpondu zen. Beraz, issue hau itxitzat joko dugu.
