### ISSUE TITLE
Euskaltzaindiaren baliabideak egokitu/txertatu

### ISSUE THREAD

**Issue by ElhuyarItzulpenak** [euskalbar/euskalbar#261]
Euskaltzaindiak webgunea berritu du, eta Euskaltzaindiaren Hiztegiko emaitzak ez ditu bistaratzen bilaketa konbinatua egitean. Gauza bera gertatzen da Orotariko Euskal Hiztegiarekin.
Bestalde, ondo legoke Euskara Batuaren Eskuliburua ere Euskalbarren txertatzea. Hemen, esteka: https://www.euskaltzaindia.eus/index.php?option=com_ebe&view=bilaketa&task=sarrera&Itemid=1161

**Comment by msusperregi** [comment]
konpondua
