### ISSUE TITLE
Energia hiztegiaren helbidea aldatu dute

### ISSUE THREAD

**Issue by ElhuyarHiztegiak** [euskalbar/euskalbar#267]
EVE-EEE Energia hiztegiaren helbidea aldatu egin da:
Izena: EEEren Energia hiztegia
Lehen: 
https://www.eve.eus/diccionario.aspx
Orain:
 https://www.eve.eus/Hiztegia.aspx

**Comment by e-gor** [comment]
Kaixo, @Thadah! Azkenaldian Euskalbar Elhuyarrek mantentzen zuen, eta pixka bat utzita geneukan. Beraz, ongi etorria, eta eskerrik asko egin dituzun ekarpenengatik! Zuk emandako bultzada aprobetxatuta, zeuden beste akats batzuk konpontzen eta hiztegi berri batzuk gehitzen ari gara, eta laster argitaratuko dugu bertsio berri bat. Milesker!
