### ISSUE TITLE
"Shift+Enter" modu konbinatuarekin bilaketa bat egitean, enter sakatzean orrialde zuri bat erakusten du, emaitzarik gabe; bigarrenez enter sakatzean orduan bilaketaren emaitza ematen du. Kontua da lehenengo orrialde zuri horren erlaitza edo pestaña goiko barran geratzen dela. Beraz, bilaketa bakoitzarekin erlaitz zuri bat irekitzen da eta goian geratzen da.

### ISSUE THREAD

**Issue by Itzuliz** [euskalbar/euskalbar#269]

**Comment by Itzuliz** [comment]
[](url)
![irudia](https://user-images.githubusercontent.com/67266446/85276196-b3e2fd80-b481-11ea-93d9-68245edadd55.png)

**Comment by Thadah** [comment]
Kaixo Joxemari,

https://github.com/euskalbar/euskalbar/commit/3e75dcf7fc7da88391606d9cd60ba036bae8c929 commit-ak arazo hau guztiz konpontzen du. Proiektuaren arduradun bat behar da azken hobekuntza hauek denei zabaltzeko. 
Bitartean, beste arazorik edo hobekuntzarik baduzu buruan, ireki issue berri bat mesedez.

Gontzal

**Comment by asiersarasua** [comment]
@Thadah Nik argitaratu dezaket AMOn, baina akatsen bat ikusi dut oraindik bilaketa konbinatuetan.

**Comment by Thadah** [comment]
Kaixo @asiersarasua,

Ok, ez ezazu argitaratu oraindik, beste issuea begiratu eta konponduko dut.
