### ISSUE TITLE
Bilaketa konbinatuetan, UZEI sinonimoen hiztegia gaitzen denean, orri osoa deskonfiguratzen da

### ISSUE THREAD

**Issue by asiersarasua** [euskalbar/euskalbar#282]
Bilaketa konbinatuetan (Shift+Enter, Ctrl+Enter), UZEI sinonimoen hiztegia gaitzen bada, emaitzen orria deskonfiguratuta agertzen da.
Bi aukera daude: UZEI kentzea bilaketa konbinatutik, edo arazoa konpontzea.

**Comment by Thadah** [comment]
Konponduta
