### ISSUE TITLE
Akatsak azken bertsioan

### ISSUE THREAD

**Issue by ElhuyarHiztegiak** [euskalbar/euskalbar#284]
Bilaketa sinplea egitean Euskalterm '%25' gehitzen du bilaketa-kutxan eta ez du bilaketa egiten. 
Bilaketa konbinatuetan ez du Elhuyar hiztegiko informazioa itzultzen.
Bilaketa konbinatuek (Ctrl. + Enter, Shift + Enter) lehen aldian funtzionatu dute, baina gero ez.

**Comment by Thadah** [comment]
Kaixo,
Lehen akatsa begiratu eta zuzenduko da

Bigarren akatsa https://github.com/euskalbar/euskalbar/issues/276 akatsaren duplikatua da eta zuzentzeko buruan dut jada.

Azkena ez da akatsa. Orriari portaera aldatu zaio eta edukia soilik freskatzen du orain. Batzuetan arinegia da edukia freskatzen ari dela ikusteko, beraz denbora-marka edo beste elementu bisual batekin orria freskatu dela erakutsiko da.

Iradokizunik baduzu(e) orria freskatu dela nola erakusteko, mesedez erantzun issue honi

**Comment by Thadah** [comment]
Konponduta

**Comment by ElhuyarHiztegiak** [comment]
Eskerrik asko zure lanagatik. Ohartarazi digute bilaketa-kutxan zuriunea ez duela onartzen. Eskerrik asko!

**Comment by Thadah** [comment]
Bai, bbf53d9c42c509ab78e75623284631959c91699c commit-ak hori ere zuzentzen du
