### ISSUE TITLE
Euskalbar > Euskalterm-ek ez du terminorik aurkitzen

### ISSUE THREAD

**Issue by alexgabi** [euskalbar/euskalbar#286]
Denbora batetik hona Euskalbarratik abiatutako bilaketek ez dute Euskalterm-en ezer aurkitzen. Nonbait Euskaltermek galdera trunkatzeko aukeran jartzen duen % karaktere bat baizik bi eransten dio Euskalbarrak eta horren ondorioz "terminoa"%25 bihurtzen du eta ez du emaitzarik aurkitzen.
![irudia](https://user-images.githubusercontent.com/6351555/214357666-7d2a7f92-08aa-4c8e-ab19-e5a614d95eb9.png)

**Comment by Thadah** [comment]
Aupa!

Uste dut arazo hori bbf53d9c42c509ab78e75623284631959c91699c commitean konpontzen dela, baina proiektuko arduradunek ez dute 5.0.9 bertsioa kaleratu. Hedapenaren orrian 5.0.8 bertsioa dago oraindik.

![image](https://user-images.githubusercontent.com/4324514/214362469-26508b78-f165-4ef9-a6b3-cc2514b81394.png)

Ez dakit nork kaleratu dezakeen bertsio berria, baina proiektua jarduerarik gabe egon da azken 6 hilabetetan. Zure issue-a irekita utziko dut bertsio berria kaleratzen duten arte edo ixtea erabakitzen badute.

**Comment by Thadah** [comment]
5.0.9 bertsioa argitaratu da eta arazoa konpontzen duela berretsi da,
