### ISSUE TITLE
Firefox deskargatzeko loturak ez du funtzionatzen

### ISSUE THREAD

**Issue by yagomoon** [euskalbar/euskalbar#289]
Download: https://addons.mozilla.org/firefox/addon/euskalbar/ lotura sakatzerakoan Add-ona ezabatua izan dela agertzen da.

**Comment by Thadah** [comment]
Kaixo!

Mozillaren gehigarrien moderatzaile taldea gehigarria berrikusten ari da betekizun batzuk falta zaizkiolako, hirugarreneko liburutegien erabilera eta pribatutasun politika baten falta, besteak beste.
Lanean ari gara egoera hau hain bezain laster konpontzeko.

Barkatu eragozpenak.

**Comment by Thadah** [comment]
Kaixo @yagomoon:

Mozillaren moderatzaile taldeak bidalitako azken bertsioa onartu du eta denontzat eskuragarri dago berriro.
Arazorik baduzu gehigarriaren orria ikusten edo lortzen jakinarazi iezaiguzu issue honetan. Irekita utziko dut oraingoz arazoa konpondu dela berretsi arte.

**Comment by Thadah** [comment]
Zuri!

Arazoa konpondutzat jarriko dut.
